[package]
name = "sun"
version = "0.1.0"
edition = "2021"
license = "GPLv3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan = "0.11.1"
regex = "1.5.4"
lazy_static = "1.4.0"